import type { Metadata } from 'next'
import { Header, Footer } from '@rnb/ui'
import '@rnb/styles'
import { I_Link } from '@rnb/types'

const appName = 'Aetherscribe'

export const metadata: Metadata = {
    title: appName,
    description: 'Generated by create next app',
}

const navLinks: I_Link[] = [
    {
        href: '/hub',
        id: 'hub',
        label: 'Hub',
    },
    {
        href: '/my-account',
        id: 'my-account',
        label: 'My Account',
    },
    {
        href: '/settings',
        id: 'settings',
        label: 'Settings',
    },
]

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className="app-wrapper">
                <Header appName={appName} hasAuth navbarItems={navLinks} />
                {children}
                <Footer appName={appName} />
            </body>
        </html>
    )
}
