import type { Metadata } from 'next'
import { Navbar, Footer, ThemeProvider, ThemeInitializer } from '@rnb/ui'
import { I_Link } from '@rnb/types'

import '@rnb/styles'
import Logo from '@/public/aetherscribe.jpg'

// Aetherscribe-specific localStorage keys — kept here so they stay in sync
// between ThemeInitializer (runs before hydration) and ThemeProvider (React).
const THEME_KEY = 'aether-theme'
const MODE_KEY = 'aether-mode'

const appName = 'Aetherscribe'

export const metadata: Metadata = {
    title: appName,
    description: 'Generated by create next app',
}

const navLinks: I_Link[] = [
    {
        href: '/hub',
        id: 'hub',
        label: 'Hub',
    },
    {
        href: '/my-account',
        id: 'my-account',
        label: 'My Account',
    },
    {
        href: '/settings',
        id: 'settings',
        label: 'Settings',
    },
]

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <ThemeInitializer themeStorageKey={THEME_KEY} modeStorageKey={MODE_KEY} />
            </head>
            <body className="app-wrapper">
                <ThemeProvider themeStorageKey={THEME_KEY} modeStorageKey={MODE_KEY}>
                    <Navbar
                        headerIcon={Logo}
                        headerTitle={appName}
                        navItems={navLinks}
                    />
                    <main className="page-wrapper">{children}</main>
                    <Footer appName={appName} />
                </ThemeProvider>
            </body>
        </html>
    )
}
